---
name: Create a Github-release

on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: create release draft
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
